// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmmtbjgfzcjfuzybnezm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbXRiamdmemNqZnV6eWJuZXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTgxNDcsImV4cCI6MjA1ODQ3NDE0N30.3lIpVo-P8H_HjBy3JLEHa78SVwGVZU7UHxey6HPrfbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);